### ISSUE TITLE
Does this work with Python 3.5?

### ISSUE THREAD

**Issue by mrichman** [imwilsonxu/fbone#48]
OS X + Python 3.5:

When invoking `fab setup`:
`ImportError: cannot import name 'isMappingType'`

It looks like Fabric isn't compatible with Python 3.5.

**Comment by erip** [comment]
Fabric isn't supported in Python 3. The same author has released [invoke](http://www.pyinvoke.org/), which is a nice alternative.

**Comment by microdou** [comment]
[fabric3](https://pypi.python.org/pypi/Fabric3) works with Python 3.5.
